#include<iostream>
using std::string;
using std::cout;
using std::endl;

class Player
{
    private:
    // Private Attributes
    string name{};
    int xp{};
    int health{};
    
    public:
    //Methods
    void set_name(string name_val){
        name = name_val;
    }
    string get_name()const{//const so we don't change the value
        return name;
    }

    // Default Constructor
    /*If we don't provide constructor at all c++ will make a no args default constructor 
    automatically this default constructor generated by c++,does nothing,when we 
    create a object with no initialization this is the constructor that is called.*/
    // Player(){
    //     name = "None";
    //     xp = 10;
    //     health = 0;
    // }

    // Player(string name_val,int xp_val,int health_val){
    //     name = name_val;
    //     xp = xp_val;
    //     health = health_val;  
    // } 
   
};
int main(){
    Player frank{};
    frank.set_name("Frank");
    cout<<frank.get_name()<<'\n';

    Player hello{"john",97,4};
    cout<<hello.get_name();


    return 0;
}


